<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>gp</AssemblyName>
    <Version>1.1.1</Version>
    <Authors>Karlo Bartels</Authors>
    <Company>Bartels Online</Company>
    <Copyright>Copyright (c) $([System.DateTime]::UtcNow.Year) $(Company)</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GISBlox.IO.GeoParquet\GISBlox.IO.GeoParquet.csproj" />
  </ItemGroup>

</Project>
